config/routes.rb
Rails.application.routes.draw do
  # resources :subscribtions
  resources :posts
  resources :newsletters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "newsletters#feed"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticated :user do
      root 'newsletters#index', as: :authenticated_root
      get 'users/sign_out' => 'devise/sessions#destroy'
      get 'users/:user_id/profile', to: 'posts#show_profile', as: 'profile'
      get 'discover', to: 'newsletters#discover', as: 'discover'
      get 'my_newsletters', to: 'newsletters#mine', as: 'mine'
      get 'feed', to: 'newsletters#feed', as: 'feed'
      get 'newsletters/:id/posts', to: 'newsletters#posts', as: 'newsletter_posts'
      get 'newsletters/:id/posts/new', to: 'posts#new', as: 'newsletter_post_new'
      get 'newsletters/:id/subscriptions', to: 'newsletters#subscribe', as: 'newsletter_subscription_new'
      delete 'newsletters/:id/subscriptions/destroy', to: 'newsletters#unsubscribe', as: 'newsletter_subscription_destroy'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
    has_many :posts, foreign_key: "newsletters_id", dependent: :destroy
    has_many :subscriptions, foreign_key: "newsletters_id", dependent: :destroy

    # validates :r_rated, presence:true
    validates :name, presence:true
    validates :topic, presence:true
    validates :users_id, presence:true
    has_one_attached :background
end

app/controllers/newsletters_controller.rb
require 'date'

class NewslettersController < ApplicationController
  before_action :set_newsletter, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /newsletters or /newsletters.json
  def index
    @newsletters = Newsletter.joins("INNER JOIN subscriptions ON subscriptions.newsletters_id = newsletters.id AND subscriptions.users_id = #{current_user.id}")
    @subscribed = Subscription.find_by(users_id: current_user.id, newsletters_id: (params[:id]))
  end

  def discover
    birthday = current_user.birthdate
    @age = ((12*(Date.today.year- birthday.year))-(birthday.month - Date.today.month))/12 
    if @age >= 18 
      @newsletters = Newsletter.all
    else
      @newsletters = Newsletter.all.where(r_rated:false)
    end
  end

  def mine
    @newsletters = Newsletter.all.where(users_id:current_user.id)
  end

  def feed
     @newsletters = Newsletter.joins("INNER JOIN subscriptions ON subscriptions.newsletters_id = newsletters.id AND subscriptions.users_id = #{current_user.id}")
    #  @posts = {{id: 1,
    #  topic: "NEWSLETTER 1",
    #  name: "NEWSLETTER 1",
    #  description: "NEWSLETTER 1",
    #  r_rated: false,
    #  users_id: 2}}
    #  count = 0
     @posts = []
     @newsletters.each do |newsletter|
      newsletter_posts = Post.all.where(newsletters_id: newsletter.id)
      newsletter_posts.each  do |post|
        @posts.push(post)
      end
      @posts.sort_by{ |post| post.created_at }.reverse
     end
  
    # @posts = Post.all.where(newsletters_id:1)
  end

  def posts
    @posts = Post.all.where(newsletters_id: params[:id])
    @newsletter = Newsletter.find_by(id: params[:id])
  end

  # GET /newsletters/1 or /newsletters/1.json
  def show
    @subscribed = Subscription.find_by(users_id: current_user.id, newsletters_id: (params[:id]))
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters or /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)
    @newsletter.users_id = current_user.id
    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to newsletter_url(@newsletter), notice: "Newsletter was successfully created." }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1 or /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to newsletter_url(@newsletter), notice: "Newsletter was successfully updated." }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1 or /newsletters/1.json
  def destroy
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: "Newsletter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def subscribe
    respond_to do |format|
      if Subscription.find_or_create_by(users_id: current_user.id, newsletters_id: (params[:id]))
        @newsletter = Newsletter.find_by(id:params[:id])
        format.html { redirect_to newsletter_url(@newsletter), notice: "You have subscribed successfully to this newsletter!" }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  def unsubscribe
    subscription = Subscription.find_by(users_id: current_user.id, newsletters_id: (params[:id]))
    respond_to do |format|
        if subscription.destroy
          format.html { redirect_to newsletter_url(params[:newsletter]), notice: "You have unsubscribed succesfully from this newsletter!" }
          format.json { render :show, status: :ok, location: @newsletter }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @newsletter.errors, status: :unprocessable_entity }
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      begin
        @newsletter = Newsletter.find(params[:id])
      rescue
        flash[:error] = "Newsletter was deleted or it does not exist"
        redirect_to :action => :index
      end
    end

    # Only allow a list of trusted parameters through.
    def newsletter_params
      params.require(:newsletter).permit(:topic, :name, :description, :users_id, :r_rated, :background)
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_with(model: newsletter) do |form| %>
  <% if newsletter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>
      <ul>
        <% newsletter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :topic, style: "display: block" %>
    <%= form.select :topic, options_for_select(["Academic", "Disciplines", "Busines", "Communication", "Concepts", "Culture", "Economy", "Education", "Energy", "Engineering", "Entertainment", "Entities", "Ethics", "Food and drink", "Geography", "Government", "Health", "History",  "Human behavior", "Humanities", "Information", "Internet", "Knowledge", "Language", "Law", "Life", "Mass media", "Mathematic", "Military", "Nature", "People", "Philosophy", "Politics", "Religion", "Science",  "Society",  "Sports", "Technology",  "Time Universe"], newsletter.topic) %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, size: 50%>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
     <%= form.text_area :description, :cols => "70", :rows => "8" %>
  </div>
  <div>
    <p>Newsletter background:</p>
    <%= form.file_field :background %> <br/>
    <%= image_tag(newsletter.background, width: "200", height: "auto") if newsletter.background.attached?%>
  </div>
  <br/>
  <div>
    <label>+18 Rated</label> <br/>
    <%= form.select :r_rated, options_for_select([[:false],[:true]], newsletter.r_rated) %>
  </div><br/>
  <div>
    <%= form.submit class:'btn btn-success float-right' %>
  </div>
<% end %>

app/views/newsletters/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark  bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/feed">NEWSLETTER</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Feed</a>
        </li>
        <li class="nav-item justify-content-end" >
          <a class="nav-link" href="/discover">Discover</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/my_newsletters">My newsletters</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/newsletters/index">My subscriptions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/newsletters/new">Create a newsletter</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/users/edit">My Profile</a>
        </li>
        <li class="nav-item justify-content-end" >
          <a class="nav-link" href="/users/sign_out">Log out</a>
        </li>
        <%= image_tag(current_user.avatar, width: "40px", height: "40px") if current_user.avatar.attached?%>
      </ul>
    </div>
  </div>
</nav>

app/views/newsletters/_newsletter.html.erb
<div id="<%= dom_id newsletter %>">
  <h4>
    <strong> <%= link_to "#{newsletter.name}", newsletter_path(newsletter) , {:style=>'text-decoration:none' } %></strong><br/>
  </h4>
  <p>
    <strong>Topic:</strong>
    <%= newsletter.topic %>
    <br/>
    <strong>Description:</strong>
    <%= newsletter.description %>
    <br/>
    <strong>Author:</strong> <% @username = User.find_by(id:newsletter.users_id).email %>
    <strong> <%= link_to "#{@username}", profile_path(:user_id => newsletter.users_id) %></strong><br/>
    <strong>Post date: </strong><%= newsletter.created_at.to_date %><br/>
    <% @amount = Post.all.where(newsletters_id:newsletter.id).count %>
    <strong> Amount of posts published:</strong> <%= @amount%>
    <br/>
  </p>
</div>

app/views/newsletters/discover.html.erb
 <%= render "navbar" %>
<div class="container"><br/>
  <p style="color: green"><%= notice %></p>
  <h1  style="color: #f09c0c">Discover some newsletters you may be interested in...</h1> <br/>
  <div id="newsletters">
    <div class="container">
      <% @newsletters.each do |newsletter| %>
        <div class="bg-light p-3 border bg-light" >
          <div class="row">
            <div class="col-8">
              <%= render newsletter %>
            </div>
            <br/>
            <div class="col align-self-end col col-lg-2">
              <%= image_tag(newsletter.background, width: "300px", height: "auto", class:"justify-content-end") if newsletter.background.attached?%><br/>
            </div>
          </div>
          <div class="row">
            <div class="col-md-auto">
              <%= button_to "Edit this newsletter", edit_newsletter_path(newsletter), method: :get, class:'btn btn-sm btn-secondary float-right' if newsletter.users_id == current_user.id%>
            </div>
            <div class="col-md-auto">
              <%= button_to "Destroy this newsletter", newsletter, method: :delete, class:'btn btn-sm btn-danger float-right' if newsletter.users_id == current_user.id%>
              <% button_to "Show this newsletter", newsletter, method: :get, class:'btn btn-secondary float-right' %>
            </div>
          </div>
        </div>
        <br/>
      <% end %>
    </div>

app/views/newsletters/edit.html.erb
 <%= render "navbar" %>
 <br/>
<div class="container">
  <h1>Editing newsletter</h1>
  <%= render "form", newsletter: @newsletter %>
  <br>
</div>

app/views/newsletters/feed.html.erb
 <%= render "navbar" %>
<div class="container"><br/>
  <p style="color: green"><%= notice %></p>
  <h1>FEED</h1>
  <div id="posts"  >
    <div class="">
      <% if @posts.length == 0 %>
        <div style="text-align:center" >
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <strong>
            <h2 class="text-muted">It seems that you aren't subscribed to any newsletter</h2>
          </strong>
          <h5 class="text-muted">Click the button below to discover some newsletters!</h5>
          <br/>
          <%= link_to 'DISCOVER',  discover_path(), class:'btn btn-lg btn-outline-secondary'%>
        </div>
      <% else%>
        <% @posts.each do |post| %>
          <div class="bg-light p-3 border bg-light" >
            <div class="row">
              <div class="col-8">
                <%= render post %>
              </div>
              <br/>
              <div class="col align-self-end col col-lg-2">
                <%= image_tag(post.image, width: "300px", height: "auto", class:"justify-content-end") if post.image.attached?%><br/>
              </div>
            </div>
            <div class="row">
              <div class="col-md-auto">
                <%= button_to "Edit this post", edit_post_path(post), method: :get, class:'btn btn-sm btn-secondary float-right' if post.users_id == current_user.id%>
              </div>
              <div class="col-md-auto">
                <%= button_to "Destroy this post", @post, method: :delete, class:'btn btn-sm btn-danger float-right' if post.users_id == current_user.id%>
                <% button_to "Show this post", post, method: :get, class:'btn btn-secondary float-right' %>
              </div>
            </div>
          </div>
          <br/>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/newsletters/index.html.erb
<%= render "navbar" %>
<div class="container"><br/>
  <p style="color: green"><%= notice %></p>
 <br/> <h1>Newsletters I'm subscribed</h1>
  <div id="newsletters"  >
    <% if @newsletters.length == 0 %>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-12">
            <div style="text-align:center" >
            <br/><br/><br/><br/><br/><br/>
              <strong>
                <h2 class="text-muted">It seems that you aren't subscribed to any newsletter</h2>
              </strong>
              <h5 class="text-muted">Click the button below to discover some newsletters!</h5>
              <br/>
              <%= link_to 'DISCOVER',  discover_path(), class:'btn btn-lg btn-outline-secondary'%>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
      <% else%>
        <% @newsletters.each do |newsletter| %>
          <div class="bg-light p-3 border bg-light" >
            <div class="row">
              <div class="col-8">
                <%= render newsletter %>
              </div>
              <br/>
              <div class="col align-self-end col col-lg-2">
                <%= image_tag(newsletter.background, width: "300px", height: "auto", class:"justify-content-end") if newsletter.background.attached?%><br/>
              </div>
            </div>
            <div class="row">
              <div class="col-md-auto">
                <%= button_to "Edit this newsletter", edit_newsletter_path(newsletter), method: :get, class:'btn btn-sm btn-secondary float-right' if newsletter.users_id == current_user.id%>
              </div>
              <div class="col-md-auto">
                <%= button_to "Destroy this newsletter", newsletter, method: :delete, class:'btn btn-sm btn-danger float-right' if newsletter.users_id == current_user.id%>
                <% button_to "Show this newsletter", newsletter, method: :get, class:'btn btn-secondary float-right' %>
              </div>
            </div>
          </div>
          <br/>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/newsletters/mine.html.erb
<%= render "navbar" %>
<div class="container"><br/>
  <p style="color: green"><%= notice %></p>
  <h1>My Newsletters</h1><br/>
  <div id="newsletters">
    <% if @newsletters.length == 0 %>
      <div style="text-align:center" >
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <strong>
          <h3 class="text-muted">Oh! It seems that you have not created newsletter yet, click below to create a new one and  <br/>
            START SHARING TODAY!</h3>
        </strong>
        <h5 class="text-muted">Click the button below to discover some newsletters!</h5>
        <br/>
        <br/>
        <br/>
        <%= link_to 'Create a new newsletter',  new_newsletter_path, class:'btn btn-lg btn-outline-secondary'%>
      </div>
      <h4></h4>
    <% else %>
      <% @newsletters.each do |newsletter| %>
       
<div class="container">
    <div class="bg-light p-3 border bg-light" >
      <div class="row">
        <div class="col-8">
          <%= render newsletter %>
        </div>
        <br/>
        <div class="col align-self-end col col-lg-2">
          <%= image_tag(newsletter.background, width: "300px", height: "auto", class:"justify-content-end") if newsletter.background.attached?%><br/>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <%= button_to "Edit this newsletter", edit_newsletter_path(newsletter), method: :get, class:'btn btn-sm btn-secondary float-right' if newsletter.users_id == current_user.id%>
        </div>
        <div class="col-md-auto">
          <%= button_to "Destroy this newsletter", newsletter, method: :delete, class:'btn btn-sm btn-danger float-right' if newsletter.users_id == current_user.id%>
          <% button_to "Show this newsletter", newsletter, method: :get, class:'btn btn-secondary float-right' %>
        </div>
      </div>
    </div>
    <br/>
</div>

      <% end %>
    <% end %>
  </div>
</div>

app/views/newsletters/new.html.erb
 
 <%= render "navbar" %>
<div class="container">
<br>
  <h1>Create a newsletter</h1>
  <%= render "form", newsletter: @newsletter %>
  <br>
</div>

app/views/newsletters/posts.html.erb
<%= render "navbar" %>
<div id="posts">
  <div class="container">
  <br/>
    <p style="color: green"><%= notice %></p>
    <h1>Posts of  <strong><%=@newsletter.name %></strong></h1>
                          <div class="col-md-auto">
                  <%= link_to "New post", newsletter_post_new_path(), class:'btn btn-success float-right' %>
                </div>
                <br/><br/>
    <div id="posts"  >
      <div class="">
        <% if @posts.length == 0 %>
          <div style="text-align:center" >
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <strong>
              <h2 class="text-muted">It seems that there is still any post here! BE THE FIRST ONE!</h2>
            </strong>
            <h5 class="text-muted">Click the button below to discover some newsletters!</h5>
            <br/>
            <%= link_to 'DISCOVER',  discover_path(), class:'btn btn-lg btn-outline-secondary'%>
          </div>
        <% else%>
          <% @posts.each do |post| %>
            <div class="bg-light p-3 border bg-light" >
              <div class="row">
                <div class="col-8">
                  <%= render post %>
                </div>
                <br/>
                <div class="col align-self-end col col-lg-2">
                  <%= image_tag(post.image, width: "300px", height: "auto", class:"justify-content-end") if post.image.attached?%><br/>
                </div>
              </div>
              <div class="row">

                <div class="col-md-auto">
                  <%= button_to "Edit this post", edit_post_path(post), method: :get, class:'btn btn-sm btn-secondary float-right' if post.users_id == current_user.id%>
                </div>
                <div class="col-md-auto">
                  <%= button_to "Destroy this post", post, method: :delete, class:'btn btn-sm btn-danger float-right' if post.users_id == current_user.id%>
                  <% button_to "Show this post", post, method: :get, class:'btn btn-secondary float-right' %>
                </div>
                <% link_to "Show this post", post %>
              </div>
            </div>
            <br/>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/newsletters/show.html.erb
<%= render "navbar" %>
<br/>
<div class="container">
  <p style="color: green"><%= notice %></p>
  <%= render @newsletter %>
          <div class="col align-self-end col col-lg-2">
          <%= image_tag(@newsletter.background, width: "300px", height: "auto", class:"justify-content-end") if @newsletter.background.attached?%><br/>
        </div><br/>
      <div class="col-md-auto">
      <%= button_to 'Subscribe',  newsletter_subscription_new_path(:newsletter => @newsletter,:newsletter_id => @newsletter.id), method: :get, class:'btn btn-lg btn-success float-right' unless @subscribed%>
    </div>
    <div class="col-md-auto">
      <%= button_to 'Unsubscribe',  newsletter_subscription_destroy_path(:newsletter => @newsletter,:newsletter_id => @newsletter.id), method: :delete, :action => 'unsubscribe', class:'btn btn-lg btn-warning float-right' if @subscribed %>
    </div>
    <br/>
  <div class="row">
    <div class="col-md-auto">
      <%= link_to 'Create a new post',  newsletter_post_new_path(), class:'btn btn-outline-success' %>
    </div>
    <div class="col-md-auto">
      <%= link_to "Posts of this newsletter", newsletter_posts_path(@newsletter), class:'btn btn-outline-warning' %> 
    </div>

    <div class="col-md-auto">
      <%= button_to "Edit this newsletter", edit_newsletter_path(@newsletter), method: :get, class:'btn  btn-secondary float-right' if @newsletter.users_id == current_user.id%>
    </div>
    <div class="col-md-auto">
      <%= button_to "Destroy this newsletter", @newsletter, method: :delete, class:'btn  btn-danger float-right' if @newsletter.users_id == current_user.id%>
      <% button_to "Show this newsletter", @newsletter, method: :get, class:'btn btn-secondary float-right' %>
    </div>
  </div>
</div>