config/routes.rb
Rails.application.routes.draw do
  # resources :subscribtions
  resources :posts
  resources :newsletters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "newsletters#feed"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticated :user do
      root 'newsletters#index', as: :authenticated_root
      get 'users/sign_out' => 'devise/sessions#destroy'
      get 'users/:user_id/profile', to: 'posts#show_profile', as: 'profile'
      get 'discover', to: 'newsletters#discover', as: 'discover'
      get 'my_newsletters', to: 'newsletters#mine', as: 'mine'
      get 'feed', to: 'newsletters#feed', as: 'feed'
      get 'newsletters/:id/posts', to: 'newsletters#posts', as: 'newsletter_posts'
      get 'newsletters/:id/posts/new', to: 'posts#new', as: 'newsletter_post_new'
      get 'newsletters/:id/subscriptions', to: 'newsletters#subscribe', as: 'newsletter_subscription_new'
      delete 'newsletters/:id/subscriptions/destroy', to: 'newsletters#unsubscribe', as: 'newsletter_subscription_destroy'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
    validates :users_id, presence:true
    validates :newsletters_id, presence:true
    validates :title, presence:true
    validates :description, presence:true
    has_one_attached :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end
  def show_profile
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.users_id = current_user.id
    respond_to do |format|
      if @post.save
        @author = User.find_by(id:@post.users_id)
        PostMailer.with(author: @author, post:@post).post_created.deliver_now
        format.html { redirect_to newsletter_posts_path(Newsletter.find_by(id:@post.newsletters_id)), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to newsletter_posts_path(Newsletter.find_by(id:@post.newsletters_id)), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to newsletter_posts_path(Newsletter.find_by(id:@post.newsletters_id)), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      begin
        @post = Post.find(params[:id])
      rescue
        flash[:error] = "User not found"
        redirect_to :action => :index
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :newsletters_id, :users_id, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :newsletters_id, value: params[:id] if @action == "new"%>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, size: 50 %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, :cols => "100", :rows => "10" %>
  </div>
  <div>
    <p>Post image:</p>
    <%= form.file_field :image %><br/>
    <%= image_tag(post.image, width: "300px") if post.image.attached?%>
  </div>
  <br/>
  <div>
    <%= form.submit class:'btn btn-lg btn-success float-right'%>
  </div>
<% end %>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark  bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/feed">NEWSLETTER</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Feed</a>
        </li>
        <li class="nav-item justify-content-end" >
          <a class="nav-link" href="/discover">Discover</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/my_newsletters">My newsletters</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/newsletters/index">My subscriptions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/newsletters/new">Create a newsletter</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/users/edit">My Profile</a>
        </li>
        <li class="nav-item justify-content-end" >
          <a class="nav-link" href="/users/sign_out">Log out</a>
        </li>
        <%= image_tag(current_user.avatar, width: "40px", height: "40px") if current_user.avatar.attached?%>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" >
  <p>
    <% @username = User.find_by(id:post.users_id).email %>
    <strong> <%= link_to "#{@username}", profile_path(:user_id => post.users_id) %></strong><br/>
    <%= post.created_at.to_date %>
    <strong> FROM:</strong><% @newsletter = Newsletter.find_by(id:post.newsletters_id) %>
    <%= link_to "#{@newsletter.name}", newsletter_path(@newsletter), {:style=>'text-decoration:none' } %></strong><br/>
</p>
<h4>
  <%= post.title %>
</h4>
<p>
  <%= post.description %>
</p>
</div>

app/views/posts/edit.html.erb
 <%= render "navbar" %>
<div class="container">
  <br/>

      <div>
    <% link_to "Show this post", @post %>
    <%= link_to "Back to posts", :back , class:'btn btn-outline-warning' %> 
  </div>
    <br/>
  <h1>Editing post</h1>
  <%= render "form", post: @post %>
  <br>

</div>
 <br>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Posts</h1>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>
<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
 <%= render "navbar" %>
<div class="container">
<br/>
  <h1>New post</h1>
  <% @action = "new" %>
  <%= render "form", post: @post %>
  <br>
  <div>
   <%= link_to "Go back to the newsletter", :back , class:'btn btn-outline-warning' %> 
  </div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/posts/show_profile.html.erb
 <%= render "navbar" %>
<div class="container ">
<br/>
  <div class="row bg-light p-3 border bg-light">
    <div class="col-md-auto">
      <% @user  = User.find_by(id: params[:user_id]) %>
      <%= image_tag(@user.avatar, width: "200px") if @user.avatar.attached?%>
    </div>
    <div class="col-md-auto">
    <br/><br/>
      <p>
        <strong>EMAIL:</strong>
        <%= @user.email %>
      </p>
      <p>
        <strong>BIO:</strong>
        <%= @user.bio %>
      </p>
      <p>
        <strong>Amount of posts:</strong>
        <%= Post.all.where(users_id:@user.id).count %>
      </p>
     </div>
  </div>
  <br/>
  <p style="color: green"><%= notice %></p>